#!/usr/bin/env python3
"""Generate files/wand_sprite_meta.lua: sprite path -> displayed art height (px).

The wand-box height model needs each wand's art height (BOX.h_pad +
BOX.s_scale * h, floored at BOX.min_h). Reading it at runtime via
GuiGetImageDimensions proved unreliable (a 13px-art wand read as the
9px fallback in-game 2026-06-12, shifting its brackets 5.6 GUI high), so
the heights are precomputed here from data.wak instead and the runtime
read demoted to a fallback for modded wands.

Covers every image under data/items_gfx/: pngs by their pixel height,
sprite xmls (the starting wands' image_file is e.g. handgun.xml) by the
frame_height of their default RectAnimation.
"""
import re
import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from gen_icons import load_wak, decode_png

MAX_H = 30  # sanity cap, matches the runtime read's guard


def xml_frame_height(src):
    """frame_height of the rect animation named by rect_animation= /
    name="default", else the first RectAnimation in the file."""
    default = re.search(r'<Sprite[^>]*\brect_animation="([^"]*)"', src)
    want = default.group(1) if default else "default"
    first = None
    for m in re.finditer(r"<RectAnimation\b[^>]*>", src):
        tag = m.group(0)
        name = re.search(r'\bname="([^"]*)"', tag)
        fh = re.search(r'\bframe_height="(\d+)"', tag)
        if not fh:
            continue
        if first is None:
            first = int(fh.group(1))
        if name and name.group(1) == want:
            return int(fh.group(1))
    return first


def main():
    wak = load_wak()
    out = {}
    for path, data in sorted(wak.items()):
        if not path.startswith("data/items_gfx/"):
            continue
        if path.endswith(".png"):
            try:
                _, h, _ = decode_png(data)
            except Exception:
                continue
            if 0 < h < MAX_H:
                out[path] = h
        elif path.endswith(".xml"):
            h = xml_frame_height(data.decode("utf-8", "replace"))
            if h and 0 < h < MAX_H:
                out[path] = h

    dst = __file__.rsplit("/", 2)[0] + "/files/wand_sprite_meta.lua"
    with open(dst, "w", newline="\n") as f:
        f.write("-- AUTO-GENERATED by tools/gen_wand_sprite_meta.py."
                " Do not edit by hand.\n")
        f.write("-- image_file/sprite_file path -> displayed art height in"
                " px, for the\n")
        f.write("-- wand-box height model (every data/items_gfx png +"
                " sprite xml).\n")
        f.write("return {\n")
        for path, h in sorted(out.items()):
            f.write('\t["%s"] = %d,\n' % (path, h))
        f.write("}\n")
    print("wrote %s (%d entries)" % (dst, len(out)))


if __name__ == "__main__":
    main()
