#!/usr/bin/env python3
"""Generate files/wand_sprite_meta.lua: sprite path -> art width+height (px).

The wand-box geometry model needs each wand's W+H, not its height: the
header draws the wand rotated 45 deg (at 1.5 GUI/px), so the box grows
with the art's DIAGONAL bbox, 0.7071*(w+h). Pixel-proven 2026-06-12:
wand_0430.png is 14x9 -- only 9px TALL, yet its box is ~3u taller than
the floor; the v8-era "2u per px of art height" law keyed on the wrong
variable. Precomputed from data.wak; the runtime GuiGetImageDimensions
read stays as a fallback for modded wands.

Covers every image under data/items_gfx/: pngs by their pixel w+h,
sprite xmls (the starting wands' image_file is e.g. handgun.xml) by the
frame_width+frame_height of their default RectAnimation.
"""
import re
import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from gen_icons import load_wak, decode_png

MAX_DIM = 30  # per-dimension sanity cap, matches the runtime read's guard


def xml_frame_wh(src):
    """frame_width+frame_height of the rect animation named by
    rect_animation= / name="default", else the first RectAnimation."""
    default = re.search(r'<Sprite[^>]*\brect_animation="([^"]*)"', src)
    want = default.group(1) if default else "default"
    first = None
    for m in re.finditer(r"<RectAnimation\b[^>]*>", src):
        tag = m.group(0)
        name = re.search(r'\bname="([^"]*)"', tag)
        fw = re.search(r'\bframe_width="(\d+)"', tag)
        fh = re.search(r'\bframe_height="(\d+)"', tag)
        if not (fw and fh):
            continue
        wh = int(fw.group(1)) + int(fh.group(1))
        if first is None:
            first = wh
        if name and name.group(1) == want:
            return wh
    return first


def main():
    wak = load_wak()
    out = {}
    for path, data in sorted(wak.items()):
        if not path.startswith("data/items_gfx/"):
            continue
        if path.endswith(".png"):
            try:
                w, h, _ = decode_png(data)
            except Exception:
                continue
            if 0 < h < MAX_DIM and 0 < w < MAX_DIM:
                out[path] = w + h
        elif path.endswith(".xml"):
            wh = xml_frame_wh(data.decode("utf-8", "replace"))
            if wh and 0 < wh < 2 * MAX_DIM:
                out[path] = wh

    dst = __file__.rsplit("/", 2)[0] + "/files/wand_sprite_meta.lua"
    with open(dst, "w", newline="\n") as f:
        f.write("-- AUTO-GENERATED by tools/gen_wand_sprite_meta.py."
                " Do not edit by hand.\n")
        f.write("-- image_file/sprite_file path -> art WIDTH+HEIGHT in px."
                " The wand box\n")
        f.write("-- grows with the 45-deg-rotated art's diagonal bbox,"
                " 0.7071*(w+h)\n")
        f.write("-- (every data/items_gfx png + sprite xml).\n")
        f.write("return {\n")
        for path, h in sorted(out.items()):
            f.write('\t["%s"] = %d,\n' % (path, h))
        f.write("}\n")
    print("wrote %s (%d entries)" % (dst, len(out)))


if __name__ == "__main__":
    main()
