#!/usr/bin/env python3
"""Generate files/wand_sprite_meta.lua: sprite path -> art HEIGHT (thickness, px).

2026-06-17: the wand-box geometry model is driven by sprite THICKNESS (the art
HEIGHT), NOT the diagonal 0.7071*(w+h). Measured ground truth (thickness -> box
height in units): h7 -> ~35.6, h9 -> 38.2, h15 -> 45.6, i.e. box_h = 26.9 +
1.25*h. The old diagonal law averaged width and thickness, so a long-thin wand
and a short-fat wand (same w+h) got the same box yet render differently; keying
on thickness separates them. Precomputed from data.wak; the runtime
GuiGetImageDimensions read (which returns w AND h separately) stays as the live
fallback for modded/changed wands, so this stays correct across game updates.

Covers every image under data/items_gfx/: pngs by their pixel HEIGHT, sprite
xmls (the starting wands' image_file is e.g. handgun.xml) by the HEIGHT of the
PNG they reference (<Sprite filename=...>) -- the engine sizes the wand box by
the image, not the RectAnimation frame (frame_height undersized starter wands;
fixed 2026-06-19). frame_height is used only if the png can't be read.
"""
import re
import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from gen_icons import load_wak, decode_png

MAX_DIM = 30  # per-dimension sanity cap, matches the runtime read's guard


def xml_png_h(src, wak):
    """HEIGHT of the PNG named by <Sprite filename="...">. The inventory wand
    panel is sized by the sprite IMAGE (what GuiGetImageDimensions returns at
    runtime), NOT the RectAnimation frame: a starter wand's handgun.xml frame is
    6px but its png is 8px, and the live box measures the 8px height (box_h
    36.9u, confirmed with the middle-click tool 2026-06-19). Keying xml sprites
    on frame_height undersized the box and drifted the whole wand stack down.
    Returns None if the filename is missing or the png won't decode (caller then
    falls back to frame_height)."""
    m = re.search(r'<Sprite\b[^>]*\bfilename="([^"]+)"', src)
    if not m:
        return None
    data = wak.get(m.group(1))
    if not data:
        return None
    try:
        _w, h, _ = decode_png(data)
    except Exception:
        return None
    return h


def xml_frame_h(src):
    """frame_height of the rect animation named by rect_animation= /
    name="default", else the first RectAnimation."""
    default = re.search(r'<Sprite[^>]*\brect_animation="([^"]*)"', src)
    want = default.group(1) if default else "default"
    first = None
    for m in re.finditer(r"<RectAnimation\b[^>]*>", src):
        tag = m.group(0)
        name = re.search(r'\bname="([^"]*)"', tag)
        fh = re.search(r'\bframe_height="(\d+)"', tag)
        if not fh:
            continue
        h = int(fh.group(1))
        if first is None:
            first = h
        if name and name.group(1) == want:
            return h
    return first


def main():
    wak = load_wak()
    out = {}
    for path, data in sorted(wak.items()):
        if not path.startswith("data/items_gfx/"):
            continue
        if path.endswith(".png"):
            try:
                w, h, _ = decode_png(data)
            except Exception:
                continue
            if 0 < h < MAX_DIM and 0 < w < MAX_DIM:
                out[path] = h
        elif path.endswith(".xml"):
            src = data.decode("utf-8", "replace")
            # png height = what the engine sizes the box by; frame_height only
            # if the backing png is missing/undecodable. A spritesheet png taller
            # than MAX_DIM is dropped (matches the runtime read's >=30 reject) --
            # none of those are carriable wand sprites.
            h = xml_png_h(src, wak)
            if not h:
                h = xml_frame_h(src)
            if h and 0 < h < MAX_DIM:
                out[path] = h

    dst = __file__.rsplit("/", 2)[0] + "/files/wand_sprite_meta.lua"
    with open(dst, "w", newline="\n") as f:
        f.write("-- AUTO-GENERATED by tools/gen_wand_sprite_meta.py."
                " Do not edit by hand.\n")
        f.write("-- image_file/sprite_file path -> art HEIGHT (thickness) in px."
                " The wand\n")
        f.write("-- box height grows with sprite THICKNESS: box_h = 26.9 +"
                " 1.25*h\n")
        f.write("-- (every data/items_gfx png + sprite xml).\n")
        f.write("return {\n")
        for path, h in sorted(out.items()):
            f.write('\t["%s"] = %d,\n' % (path, h))
        f.write("}\n")
    print("wrote %s (%d entries)" % (dst, len(out)))


if __name__ == "__main__":
    main()
