#!/usr/bin/env python3
"""Extract per-spell structural metadata from Noita's gun_actions.lua.

The cast engine (data/scripts/gun/gun.lua) builds a wand's shot by popping
cards off one flat deck in order. Structure comes from two mechanisms:

  * DRAW_MANY cards (multicast) call draw_actions(N) -> the next N drawn cards
    join the same shot as a group.
  * Trigger/timer projectiles call add_projectile_trigger_*(entity, [delay,]
    count) -> draw_shot(create_shot(count)), a NESTED sub-shot of `count`
    cards drawn as the trigger payload.
  * Modifiers mutate shot state -> they prefix-attach to the next projectile.

So a wand's deck parses like a Lisp token stream: multicast/trigger counts
introduce sub-expressions. This script captures, per action id:
    type   - ACTION_TYPE_* (PROJECTILE/MODIFIER/DRAW_MANY/...)
    group  - N, for DRAW_MANY multicast cards (how many siblings they gather)
    payload/trigger - N + kind, for trigger projectiles (nested sub-shot size)

Output: files/structure_meta.lua (a Lua table the mod loads at runtime).
Pure stdlib. Run from anywhere; paths derive from this file's location.
"""
import struct, re, os, sys

MOD = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WAK = (sys.argv[1] if len(sys.argv) > 1 else
       os.environ.get("NOITA_WAK",
       os.path.normpath(os.path.join(MOD, "..", "..", "data", "data.wak"))))
OUT = os.path.join(MOD, "files", "structure_meta.lua")


def read_gun_actions():
    buf = open(WAK, "rb").read()
    count = struct.unpack_from("<I", buf, 4)[0]
    pos = 16
    for _ in range(count):
        off, size, plen = struct.unpack_from("<III", buf, pos); pos += 12
        name = buf[pos:pos+plen].decode("utf-8", "replace"); pos += plen
        if name == "data/scripts/gun/gun_actions.lua":
            return buf[off:off+size].decode("utf-8", "replace")
    raise SystemExit("gun_actions.lua not found in wak")


def parse(src):
    # Drop block comments so commented-out template actions are ignored.
    src = re.sub(r'--\[\[.*?\]\]', '', src, flags=re.S)
    marks = [(m.start(), m.group(1)) for m in re.finditer(r'\bid\s*=\s*"([^"]+)"', src)]
    out = {}
    for i, (st, aid) in enumerate(marks):
        end = marks[i+1][0] if i+1 < len(marks) else len(src)
        body = src[st:end]
        t = re.search(r'\btype\s*=\s*(ACTION_TYPE_\w+)', body)
        typ = t.group(1).replace("ACTION_TYPE_", "") if t else "OTHER"
        rec = {"type": typ}
        nm = re.search(r'\bname\s*=\s*"([^"]*)"', body)
        if nm:
            rec["name"] = nm.group(1)
        # How many extra cards this action force-draws (draw_actions(N, true)).
        # This, not the action type, is what makes a card chain or multicast:
        # all PASSIVEs and almost all MODIFIERs draw 1 (RANDOM_MODIFIER doesn't),
        # and some OTHER/UTILITY cards (ALPHA, I_SHOT, ...) draw 1 too.
        # BURST_X draws #deck (the whole remaining deck) -> encoded as -1.
        dm = re.search(r'draw_actions\(\s*(\d+|#deck)', body)
        if dm:
            rec["draws"] = -1 if dm.group(1) == "#deck" else int(dm.group(1))
        if typ == "DRAW_MANY" and rec.get("draws"):
            rec["group"] = rec["draws"]
        tg = re.search(r'add_projectile_trigger_(timer|hit_world|death)\([^)]*?(\d+)\s*\)', body)
        if tg:
            rec["trigger"] = tg.group(1)
            rec["payload"] = int(tg.group(2))
        out[aid] = rec
    return out


def to_lua(meta):
    def fmt(rec):
        parts = ['type="%s"' % rec["type"]]
        if "name" in rec:    parts.append('name="%s"' % rec["name"])
        if "draws" in rec:   parts.append("draws=%d" % rec["draws"])
        if "group" in rec:   parts.append("group=%d" % rec["group"])
        if "payload" in rec: parts.append('trigger="%s", payload=%d' % (rec["trigger"], rec["payload"]))
        return "{ " + ", ".join(parts) + " }"
    lines = [
        "-- AUTO-GENERATED by tools/gen_structure_meta.py. Do not edit by hand.",
        "-- Per-spell structural metadata used to parse a wand's deck into a tree.",
        "-- type: PROJECTILE/STATIC_PROJECTILE/MODIFIER/DRAW_MANY/MATERIAL/UTILITY/PASSIVE/OTHER",
        "-- draws: how many cards the action force-draws (1 = chains like a",
        "--        modifier; >=2 = multicast; -1 = the whole remaining deck).",
        "-- group: multicast draw count (DRAW_MANY). trigger/payload: nested sub-shot.",
        "return {",
    ]
    for aid in sorted(meta):
        lines.append('\t["%s"] = %s,' % (aid, fmt(meta[aid])))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    meta = parse(read_gun_actions())
    open(OUT, "w").write(to_lua(meta))
    n_group = sum("group" in r for r in meta.values())
    n_trig = sum("payload" in r for r in meta.values())
    print(f"wrote structure_meta.lua: {len(meta)} actions "
          f"({n_group} multicast, {n_trig} trigger)")


if __name__ == "__main__":
    main()
